### ISSUE TITLE
Pandoc-citeproc no longer part of pandoc

### ISSUE THREAD

**Issue by shmalebx9** [phiresky/pandoc-url2cite#4]
It seems the [newest](https://pandoc.org/releases.html#pandoc-2.11-2020-10-11) version of pandoc replaces pandoc-citeproc with citeproc. Pandoc-url2cite now complains that it cannot find pandoc-citeproc and exits when running with pandoc.

**Comment by phiresky** [comment]
Thank you. 

The code was using citeproc to convert bibtex to CSL JSON:

    pandoc-citeproc --bib2json --format=biblatex

I've replaced that with `pandoc --from=biblatex --to=csljson` which seems to work the same way.


I've also replaced `--filter=pandoc-citeproc` with `--citeproc` in the examples since it is now integrated.
